version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: Dockerfile.test
    command: dockerize -wait tcp://test-db:3306 bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true #pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - test-db
      - selenium_chrome
    links: 
      - test-db
    ports:
      - "3001:3000"
    volumes:
      - ..:/var/www/rails/myapp:cached # ソースコード変更したらDocker側も即反映されるように

  test-db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: docker_test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: yuki
      MYSQL_PASSWORD: password
    ports:
      - "3306"

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
    logging:
      driver: none
