version: 2
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose -f dockertest/docker-compose.test.yml build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose -f dockertest/docker-compose.test.yml up -d
      - run:
          name: db待機
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: データベースのセットアップ
          command: docker-compose -f dockertest/docker-compose.test.yml exec web bundle exec rails db:migrate RAILS_ENV=test
      - run:
          name: RSpecテスト実行
          command: docker-compose -f dockertest/docker-compose.test.yml exec web bundle exec bin/rspec
      - run:
          name: Rubocopテスト実行
          command: docker-compose -f dockertest/docker-compose.test.yml exec web bundle exec rubocop
      - run:
          name: Dockerコンテナの停止
          command: docker-compose -f dockertest/docker-compose.test.yml down